name: generators
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  autoequal: ^0.9.1
  auto_route: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^5.0.4
  autoequal_gen: ^0.9.1
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
